# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 03:48
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_identifier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VendingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vending_machines.VendingMachine'),
        ),
    ]
