# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 04:22
from __future__ import unicode_literals

from django.db import migrations, models

import apps.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon',
            field=models.ImageField(default='', upload_to=apps.base.models.random_name_in(b'product-icons')),
            preserve_default=False,
        ),
    ]
